before_install:
  - git submodule update --init --recursive
  - npm install lessc
language: python
python:
  - 2.6
  - 2.7
install:
  - python setup.py develop
  - pip install -r requirements.txt
script:
  - make clean all

